# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z014sclg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Filippo/Desktop/Electronics/CNNLayer/CNN_ZYBO/CNN_ZYBO.cache/wt [current_project]
set_property parent.project_path C:/Users/Filippo/Desktop/Electronics/CNNLayer/CNN_ZYBO/CNN_ZYBO.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Filippo/Desktop/Electronics/CNNLayer/CNN_ZYBO/CNN_ZYBO.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property generic {InputHeight=5 InputWidth=5 FilterHeight=3 FilterWidth=3 AddressLength=4} [current_fileset]
read_vhdl -library xil_defaultlib {
  C:/Users/Filippo/Desktop/Electronics/CNNLayer/hdl/src/CNNTypes.vhd
  C:/Users/Filippo/Desktop/Electronics/CNNLayer/hdl/src/CNNMemory.vhd
  C:/Users/Filippo/Desktop/Electronics/CNNLayer/hdl/src/CNNRegister.vhd
  C:/Users/Filippo/Desktop/Electronics/CNNLayer/hdl/src/CNNLayer.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Filippo/Desktop/Electronics/CNNLayer/CNN_ZYBO/CNN_ZYBO.srcs/constrs_1/new/cnn_zybo_constraint.xdc
set_property used_in_implementation false [get_files C:/Users/Filippo/Desktop/Electronics/CNNLayer/CNN_ZYBO/CNN_ZYBO.srcs/constrs_1/new/cnn_zybo_constraint.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top CNNLayer -part xc7z014sclg400-1 -mode out_of_context


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CNNLayer.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file CNNLayer_utilization_synth.rpt -pb CNNLayer_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
